version: 2.1

orbs:
  node: circleci/node@7

executors:
  node-executor:
    docker:
      - image: cimg/node:22.14

commands:
  install-deps:
    steps:
      - node/install-packages:
          pkg-manager: pnpm
          cache-path: node_modules
          override-ci-command: pnpm install --no-frozen-lockfile

jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - run:
          name: Run Linting
          command: pnpm lint

  test:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - run:
          name: Run Tests
          command: pnpm test

  build:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - install-deps
      - run:
          name: Build application
          command: pnpm run build

workflows:
  lint-and-build:
    jobs:
      - lint
      - test
      - build:
          requires:
            - test